name: theodore
channels: 
  - openbabel
dependencies:
  - python=2.7
  - ipykernel
  - cython
  - numpy
  - scipy
  - matplotlib
  - openbabel
  - h5py
  # - pip:
  #   - "--editable=git+https://github.com/orbkit/orbkit.git"